name: Pull request check

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x.x'
          cash: npm
      - run: nom ci
      - run: nom run lint
      - run: nom run lint:types
